name: Continuous Integration
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: asdf-vm/actions/install@v2

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      #- name: Version & Publish
      #  uses: changesets/action@master
      #  with:
      #    version: pnpm run version
      #    commit: 'chore: Update Versions'
      #    title: 'chore: update versions'
      #    publish: pnpm run publish
      #  env:
      #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
