name: Continuous Integration
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nodeJs, and pnpm.
        uses: asdf-vm/actions/install@v2

      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run tsc

      - name: Test
        run: pnpm run test

      - name: Create / Publish Versions
        uses: changesets/action@master
        with:
          version: pnpm run version
          commit: 'chore: Update Versions'
          title: 'chore: update versions'
          publish: pnpm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
